### ISSUE TITLE
MQTT event handler is still active after terminate

### ISSUE THREAD

**Issue by skannea** [AppDaemon/appdaemon#1141] opened 2021-01-28 16:27 UTC
Changes in an appdaemon app makes it terminate and restart. That is also what happens in the case described here. However, when sending an MQTT message to the app, **the new as well as the terminated app instance will receive the message**. 

I have a MQTT utility app that can be used by other apps, mqttapp.py:

```
import appdaemon.plugins.mqtt.mqttapi as mqtt

class M(mqtt.Mqtt): 

  def initialize(self):
    self.set_namespace('mqtt')
      
  def terminate(self): 
    pass
    
  def subscribe( self, receiver, ontopic, **kwargs  ):  
    self.mqtt_subscribe( ontopic )
    return self.listen_event( receiver, "MQTT_MESSAGE",  topic = ontopic, **kwargs )  

  def unsubscribe( self, ontopic ):
    self.mqtt_unsubscribe( ontopic )  

  def publish( self, topic, data, ret = False, q = 0 ):
    self.mqtt_publish( topic, data, retain = ret, qos = q )

```    

The MQTT app methods are called by anoter app, mqtttest2.py:

```
import appdaemon.plugins.hass.hassapi as hass    
 
class H(hass.Hass): 
  def initialize(self):
    self.timestamp = self.get_now().isoformat()
    self.log( 'init: ' + self.timestamp )    
    self.mqtt = self.get_app("mqttapp") 
    self.mqtthandle = self.mqtt.subscribe( self.onMessage, 'test' )  
      
  def terminate(self): 
    self.log( 'terminate: ' + self.timestamp )    
    self.mqtt.unsubscribe( 'test' ) 
    self.cancel_listen_event( self.mqtthandle )    

  def onMessage( self, event_name, data, kwargs):
    self.log( 'onMessage: ' + self.timestamp )      
```

apps.yaml: 

```
mqttapp:
  module: mqttapp 
  class: M 

mqtttest:
  module: mqtttest2 
  class: H 
```

On start the app gets a timestamp that is unique for each instance.
From the log, it is obvious that both instances, or at least the event handlers, are alive.

```
2021-01-28 15:32:56.643645 INFO mqtttest: onMessage: 2021-01-28T14:32:49.065757+00:00
2021-01-28 15:32:56.611575 INFO mqtttest: onMessage: 2021-01-28T14:31:10.776171+00:00
2021-01-28 15:32:49.077521 INFO mqtttest: init: 2021-01-28T14:32:49.065757+00:00
2021-01-28 15:32:49.044255 INFO AppDaemon: Initializing app mqtttest using class H from module mqtttest2
2021-01-28 15:32:49.034161 INFO AppDaemon: Reloading Module: /config/appdaemon/apps/mqttapp/mqtttest2.py
2021-01-28 15:32:49.023253 INFO mqtttest: terminate: 2021-01-28T14:31:10.776171+00:00
2021-01-28 15:32:49.016240 INFO AppDaemon: Calling terminate() for mqtttest
2021-01-28 15:32:49.015594 INFO AppDaemon: Terminating mqtttest
2021-01-28 15:31:36.963515 INFO mqtttest: onMessage: 2021-01-28T14:31:10.776171+00:00
2021-01-28 15:31:10.782169 INFO mqtttest: init: 2021-01-28T14:31:10.776171+00:00
2021-01-28 15:31:10.748387 INFO AppDaemon: Initializing app mqtttest using class H from module mqtttest2
```
I noticed this problem some time ago but have not "isolated" it until now. 
Without communication between two apps, I have not seen this problem.

**Comment by ReneTode** [comment] 2021-01-28 16:51
you try to use cancel_liste_event on an handle that doesnt belong to that app.
so the listener from app mqttapp is never canceled.
you can only cancel listeners from inside the same app as they are started in.
so you need to create a cancel function inside your mqtt app and return the handler.

**Comment by skannea** [comment] 2021-01-28 18:31
OK, is this what you mean?

Adding following methods in mqttapp.py. Listen and cancel are now handled in mqttapp.

 ```
 def zsubscribe( self, receiver, ontopic, **kwargs  ):  
    self.logg('subscribe: ' + ontopic, 'INFO')
    self.mqtt_subscribe( ontopic )
    self.mh = self.listen_event( receiver, "MQTT_MESSAGE",  topic = ontopic, **kwargs )  

  def zunsubscribe( self, ontopic ):
    self.logg('unsubscribe: ' + ontopic, 'INFO')
    self.mqtt_unsubscribe( ontopic )  
    self.cancel_listen_event( self.mh )
 
```  
Then changing mqtttest app, using the new methods. 

```
import appdaemon.plugins.hass.hassapi as hass    
 
class H(hass.Hass): 
  def initialize(self):
    self.timestamp = self.get_now().isoformat()
    self.log( 'init: ' + self.timestamp )    
    self.mqtt = self.get_app("mqttapp") 
    self.mqtt.zsubscribe( self.onMessage, 'test' )    
      
  def terminate(self): 
    self.log( 'terminate: ' + self.timestamp )    
    self.mqtt.zunsubscribe( 'test' ) 
    #self.cancel_listen_event( self.mqtthandle )       

  def onMessage( self, event_name, data, kwargs):
    self.log( 'onMessage: ' + self.timestamp )      
```
The result is this log, showing the same behaviour:
```
2021-01-28 18:58:39.744250 INFO mqtttest: onMessage: 2021-01-28T17:58:34.109106+00:00
2021-01-28 18:58:39.715802 INFO mqtttest: onMessage: 2021-01-28T17:58:05.366678+00:00
2021-01-28 18:58:34.128309 INFO mqtttest: init: 2021-01-28T17:58:34.109106+00:00
2021-01-28 18:58:34.086380 INFO AppDaemon: Initializing app mqtttest using class H from module mqtttest2
2021-01-28 18:58:34.076570 INFO AppDaemon: Reloading Module: /config/appdaemon/apps/mqttapp/mqtttest2.py
2021-01-28 18:58:34.068021 INFO mqtttest: terminate: 2021-01-28T17:58:05.366678+00:00
2021-01-28 18:58:34.060816 INFO AppDaemon: Calling terminate() for mqtttest
2021-01-28 18:58:34.060064 INFO AppDaemon: Terminating mqtttest
2021-01-28 18:58:21.258740 INFO mqtttest: onMessage: 2021-01-28T17:58:05.366678+00:00
2021-01-28 18:58:05.383855 INFO mqtttest: init: 2021-01-28T17:58:05.366678+00:00
2021-01-28 18:58:05.344745 INFO AppDaemon: Initializing app mqtttest using class H from module mqtttest2
2021-01-28 18:58:05.335518 INFO AppDaemon: Reloading Module: /config/appdaemon/apps/mqttapp/mqtttest2.py

```
I also tried   `  self.set_namespace('mqtt') ` in the new methods. Same result.

The event handler is still in the calling app. Is that not allowed? 
In any case, if operations are not allowed, this should be detected and logged as errors.

**Comment by ReneTode** [comment] 2021-01-29 00:29
you use 1 app to strat more then 1 listener in your mqttapp.
zsubscribe should return te handle to the other app,
zunsbscribe should recieve that same handle.

so for mqttapp.py i would add:
```
def zsubscribe( self, receiver, ontopic, **kwargs  ):  
   self.logg('subscribe: ' + ontopic, 'INFO')
   self.mqtt_subscribe( ontopic )
   return self.listen_event( receiver, "MQTT_MESSAGE",  topic = ontopic, **kwargs )  

def cancel_listening(self, handle):
    self.cancel_listen_event(handle )       
```
and in mqtttest.py:
```
  def terminate(self): 
    self.log( 'terminate: ' + self.timestamp )    
    self.mqtt.cancel_listening( self.handle_you_got_from_subscribe )
    ```

**Comment by skannea** [comment] 2021-01-29 12:24
Same result I'm afraid.

I tried an even cleaner code with same result.

mqttplain:

```
class M(mqtt.Mqtt):  

  def initialize(self):
    self.set_namespace('mqtt')
     
  def terminate(self): 
    pass

```
mqtttest:

```
class H(hass.Hass): 
  def initialize(self): 
    self.timestamp = self.get_now().isoformat()      
    self.log( 'init: ' + self.timestamp )    
    self.mqtt = self.get_app("mqttplain")
    self.mqtt.mqtt_subscribe( 'test' )         
    self.mqtthandle = self.mqtt.listen_event( self.onMessage, "MQTT_MESSAGE",  topic = 'test' )  
      
  def terminate(self): 
    self.log( 'terminate: ' + self.timestamp )    
    self.mqtt.mqtt_unsubscribe( 'test' ) 
    self.mqtt.cancel_listen_event( self.mqtthandle )       

  def onMessage( self, event_name, data, kwargs):
    self.log( 'onMessage: ' + self.timestamp )      

```
What is the intended way of using the MQTT plugin? I have not found any examples.
Is mqtt a hass subclass so all hass functionality is also there?

**Comment by ReneTode** [comment] 2021-01-29 12:59
no mqtt is not a subclass, it just another plugin.
there can be more plugins (and will be in the future.)
a plugin is a connector between AD and another server (HA, MQTT, etc.)

apps that inherit from a plugin have only the api from that plugin + ADapi
so if you inherit from mqtt, you wont have access to the hass api.

you could use the new style apps and not inherit from a plugin but from adbase.
https://appdaemon.readthedocs.io/en/latest/AD_API_REFERENCE.html
then you can use api from different plugins in 1 app.

you probably run latest release, and there were known issues with double running apps, that should be solved in dev, but im still not sure if its related to this though.

and reading back i think i see the trouble.
every listener (listen_event) needs a callback in the same app.
i see you use:
```
   return self.listen_event( receiver, "MQTT_MESSAGE",  topic = ontopic, **kwargs )  
```
and i never see you define reciever anywhere.
but normally it should be self.reciever, and then a function in the same class.
using anything different will lead to unexpected trouble.
if it isnt a good defined callback it will certainly give trouble.

**Comment by skannea** [comment] 2021-01-29 23:19
" a function in the same class "
I tried to put onMessage in the mqtt class but register it from the hass class: 
`self.mqtthandle = self.mqtt.listen_event( self.mqtt.onMessage, "MQTT_MESSAGE",  topic = 'test' )  `
Same result. 
And the callback works fine in all my examples. It is the cancelling that does not work. Without a warning or error.

Looking in the AD source (events.py) I see that there is no error or even debug logging in cancel_event_callback when there is no match. It should, I think. 
 
Without knowing the details, it looks like the listening and cancelling app must be the same, but there are no other restrictions.  

Looking in mqttapi.py I see that there is an override on listen_event but not on cancel_listen_event. And there is some namespace fixing (beyond my understanding) in listen_event that is not in the cancel_listen_event. Suspect! Maybe cancel never works!
Trying the code below shows exactly this. The cancel_listen_event call has no effect and testx as well as testy messages are logged.

```
import appdaemon.plugins.mqtt.mqttapi as mqtt

class M(mqtt.Mqtt):   

  def initialize(self):
    self.set_namespace('mqtt')
    self.log( 'init: ' )    
    self.mqtt_subscribe( 'testx' ) 
    self.mqtt_subscribe( 'testy' )     
    self.mqtthandlex = self.listen_event( self.onMessage, "MQTT_MESSAGE",  topic = 'testx' )  
    self.mqtthandley = self.listen_event( self.onMessage, "MQTT_MESSAGE",  topic = 'testy' )  
    self.cancel_listen_event( self.mqtthandlex ) 
    
  def terminate(self): 
    self.log( 'terminate: ' )    

  def onMessage( self, event_name, data, kwargs):
    self.log( 'onMessage: ' + data['topic'] )      

```

**Comment by ReneTode** [comment] 2021-01-30 03:03
i cant check your test like this.
whit this app testx topic should be ignored (depending on what you got in appdaemon.yaml)
but @Odianosen25 can tell more about that.

i know that this: 
```
self.mqtthandle = self.mqtt.listen_event( self.mqtt.onMessage, "MQTT_MESSAGE", topic = 'test' )
```
is also wrong.
because self.mqtt.onMessage isnt a callback that belongs to the same class.

the only accepted way is:

```
import appdaemon.plugins.mqtt.mqttapi as mqtt

class M(mqtt.Mqtt):   
    def initialize(self):
       self.mqtthandlex = self.listen_event( self.onMessage, "MQTT_MESSAGE",  topic = 'testx' )  

  def onMessage( self, event_name, data, kwargs):
    self.log( 'onMessage: ' + data['topic'] )      
```

but i never subcribe in app myself ( i set them in appdaemon.yaml)
thats why @Odianosen25 who did write the mqtt plugin could tell more.

to me it seems more that the filter doesnt work, then that the cancel doesnt work.

**Comment by Odianosen25** [comment] 2021-01-30 06:59
@skannea,

Yes you are right the cancel event listener in MQTT doesn’t work. If you log both handlers, you will see it’s an awaitable and not an expected hex string. This has been fixed in dev, so unless you use dev or await the next release, this issue will persist I am afraid.

Regards

**Comment by skannea** [comment] 2021-01-30 10:11
@Odianosen25, thanks for the confirmation. It is no panic when you are aware of the problem. 

Please note that I have 3 observations:

1. this cancel problem
2. lack of warnings when your cancel has no match
3. poor documentation overall on how to use mqtt plugin in practise (might be a HA issue?)

Point 3, I would be happy to contribute on if I only knew how to do it in a good way.
 
I am also somewhat concerned about you saying "This has been fixed in dev". Is the procedure to fix issues without regging them as a github issue? Could have saved some effort from my side...

BTW, I think AD is a superb tool. It has introduced me to python.  
However I have some other concerns about usefulness and also for risks for "zombee apps".
 
An app's listeners are automatically cancelled when the app is terminated. A very good idea! But when a function defined in one app is the callback of a listener of another app, this will not happen. You must explicitly cancel the listening. 
@ReneTode claims that callbacks must be of the same class (do you mean in the same app instance?) as the listen_event. I can understand that auto cancelling only works if you follow this rule. 
But it also makes it almost impossible to integrate hass and mqtt. 
In my opinion a listen registration should belong to the "client app". For example: app A has some callback based functionality that is useful for app B and app C. The only useful solution is that apps B and C defines their own callback function and connects them to some events and filtering handled by A, and that they are responsible for the cancelling. When B or C terminates, auto cancelling works. If A reloads, there will be no events but this is solved with dependencies.
This is to me the common and natural way of solving such problems.
Note that A, B and C can be of the same class, typically hass.

**Comment by ReneTode** [comment] 2021-01-30 14:21
thx @Odianosen25 would have been nice if i would have know about it ;) 

> @ReneTode claims that callbacks must be of the same class (do you mean in the same app instance?) as the listen_event. I can understand that auto cancelling only works if you follow this rule.

indeed i ment the app instance. and indeed because the reinitialisation from an app, and because listeners and schedulars belong to an app, they will only be closed if they are in the same app.

> But it also makes it almost impossible to integrate hass and mqtt.

there are 2 possible ways to use HA and MQTT at the same time:
1) the old way: in an app that inherits from hass use the publish service from hass to publish, and in appdaemon.yaml set the correct event for what you want to listen to (thats your subscribe), or in an app that inherits from mqtt listen to what you want, and fire an event with the data you want to process and listen to that event in an hass inherited app.

2) the new way. that way inherits from adbase, and you get the api you want with get_plugin_api(), like:
```
import adbase as ad

class Test(ad.ADBase):

  def initialize(self):

    self.adbase = self.get_ad_api()
    self.mqtt = get_plugin_api("MQTT")
    self.hass = get_plugin_api("hass")
    handle = self.adbase.run_in(callback, 20)
    self.mqtt. listen_event(...)
    self.hass.get_state(...)
```

> In my opinion a listen registration should belong to the "client app". 

its a threaded mechanism. at this moment the function that is called with get_app runs in the thread from that app.
it makes that also all values from that app are available.

there is spoken about making it possible to call the function in the thread from the client app, but at the moment thats not possible (yet)
there is no easy solution to do so, thats why this option takes time. (which is rare for the devs at the moment)

**Comment by skannea** [comment] 2021-01-30 15:11
@ReneTode I can see that the new way is useful. I will try it. It is also something we could have in a cook book for HA users.
The old way is in my opinion not very useful for HA users. I guess it is easier to implement the mqtt stuff as HA scripts.

I shouldn't really discuss threading. It is very deep water for me. But when I look in the source code it looks as registration/cancellation is based on association with an app name. I mean that the wrong app name is used. It should be the **client** app name, or rather: the name of the app that is initiating the registration and is responsible for the cancellation. 

Or do you mean that even if callbacks to the client app seems to work fine, in reality they cause other problems that I am not aware of.

**Comment by ReneTode** [comment] 2021-01-30 16:28
> The old way is in my opinion not very useful for HA users.

actually the opposite. most HA users will do most mqtt stuff inside HA, so they only need 1 plugin.
all my apps (hundreds of them) all depend on 1 plugin, and i do almost everything in AD.
i personally also rather stick to the old way if i can, because i rather type self.listen_event then self.mqtt.listen_event or self.hass.listen_event

> It should be the client app name, or rather: the name of the app that is initiating the registration and is responsible for the cancellation.

the client appname is unknown to the app that contains the general function.
the complete function for listen_state is:
self.listen_state(self, self.CB, entity)
the appname is taken from the self argument.

and writing that i think it might be possible to connect a listener to another app by providing the app object from the client app.
but i never tried something like that.

> Or do you mean that even if callbacks to the client app seems to work fine, in reality they cause other problems that I am not aware of.

AD is so full of possibilities that even after 5 years i still learn new options every time.
but if you dont use AD as it is/was intended (in this case put the callback from a listener inside the same class as the listener), then i never can say if there are no unwanted underlying troubles rising, at some point. (the admin interface could start giving trouble, memory could fill up, listeners not canceled, etc.)
and even if troubles/issues come up when doing it different, then its not sure if they ever will be changed.

all i can do (as 1 of the most heavy users, former dev, and supporter) is tell people how it is was intended to use.
off course its up to the users if they follow that.

**Comment by Odianosen25** [comment] 2021-01-30 16:47
> thx @Odianosen25 would have been nice if i would have know about it ;)

@ReneTode yeah apologies about that, even I didn't know until this was brought to my attention [here](https://github.com/AppDaemon/appdaemon/issues/1085). I forgot to even close the issue after merging lols

That's a long one @skannea , but will try to respond in addition to what Rene has said already

> this cancel problem

Well I get that, but we did discuss allowing to cancel stuff listeners from another app (which I actually liked the idea), but dropped the idea as it could lead to confusion. So we didn't bother to do that again.

>  lack of warnings when your cancel has no match

I thought we had fixed this, ok we didn't as its only in cancel scheduler. Kindly put in an issue for it, so we remember to get it done later

> poor documentation overall on how to use mqtt plugin in practise (might be a HA issue?)

Well yes will be nice to help out on that. but really its expected most users (who are HA users) will stick to mostly ythe HA plugin. Using more than a single plugin, is not every day stuff as Rene said about, HA users will most likely do the MQTT stuff in HA anyway.

 > I am also somewhat concerned about you saying "This has been fixed in dev". Is the procedure to fix issues without regging them as a github issue? Could have saved some effort from my side...

Well sometimes its not a GitHub issue, but this one was as can be seen from the link above. Even the solution was a PR from a user.

> BTW, I think AD is a superb tool. It has introduced me to python.

Thanks for the kind words. I am same here as AD brought me into python before becoming one of the devs

> An app's listeners are automatically cancelled when the app is terminated. A very good idea! But when a function defined in one app is the callback of a listener of another app, this will not happen. You must explicitly cancel the listening.
@ReneTode claims that callbacks must be of the same class (do you mean in the same app instance?) as the listen_event. I can understand that auto cancelling only works if you follow this rule.

Well yeah pretty much. When you start linking apps like that, its always the reason we tell users to make use of the app dependency functionality. What it means is that when you have app A using app B to listen to stuff. Make app B a dependency for app A. So what this means is that when app B restarts for any reason, it will also restart app A and avoid the issue you are having.

Another way to get around this is to make use of events to share the data between app. This might not be useful here. but in scenarios where app B connects to some service and you need to feed the data back to app A. App B can send the data to app A using events, so if app B was to restart, even if app A doesn't, its all good.

Another solution is to make app B some proxy to app A, and this you do using service calls. So if you want app A to get some data or use some functions in app B, have app B register services which can easily be accessed by app A or the other way around. This way even if any was to restart, the other will always get the latest object.

The easiest and cleanest to me is to use option 1, but I have scenarios where I use all options and as Rene said, with AD almost anything is possible.

> But it also makes it almost impossible to integrate hass and mqtt.

Nope. Even before we had the new style of writing apps, I just use the `get_app` api and make the MQTT app a dependent to the HASS app and I am all good.

> In my opinion a listen registration should belong to the "client app". 

What is the point of doing this, when the client app can listen by itself? Also you miss a point somewhere, its possible to access all MQTT api from a HASS app by making use of the service call directly. 

For example from a HASS app you can use 
```
self.call_service("mqtt/publish", topic="topic", payload="bla bla", namespace="mqtt")
```

All MQTT apis are accessible using service calls, so really one is not in anyway limited to being forced to even have a MQTT app. Something goes for listening to MQTT events from within a HASS app. Just make good use of the `namespace` flag

Hope this helps

**Comment by skannea** [comment] 2021-01-30 17:20
@ReneTode 
> most HA users will do most mqtt stuff inside HA, so they only need 1 plugin.

Well that is also what I say. Adding the mqtt plugin will only give more complicated dependencies.

> the complete function for listen_state is:
> self.listen_state(self, self.CB, entity)
> the appname is taken from the self argument.
> 

Yes I know. But in my fantasy it could look like: 
```
self.serverapp = self.get_app('theserver')
self.hand = self.serverapp.listen_event(self, self.myCallback, 'THEEVENT', filter='xyz', responsible_app='myapp')

```
I still believe in the 'responsibility principle' as a fundament.

> all i can do is tell people how it is was intended to use.

Of course, I will not argue on that. Thank you for all your input in dicussions about AD. Really valuable.
But I really looked for a description on how to use MQTT plugin and couldn't understand why nobody seemed to use it.
Now I know.

**Comment by skannea** [comment] 2021-01-30 18:03
@Odianosen25, I am very impressed by your and @ReneTode 's response on the issue.
First, I really searched in the issues when I encountered the problem. I guess that was before 8 December so I missed the issue you are referring. Sorry.

> Kindly put in an issue for it

I will put an issue on the lack of no match warning.

> we tell users to make use of the app dependency functionality

In many cases A depends on B and B depends on A. Maybe not what you want if A is regarded as a server of B (and other apps). But I realise it works.

> Nope. Even before we had the new style of writing apps, I just use the get_app api and make the MQTT app a dependent to the HASS app and I am all good.

So how did MQTT tell HASS there was a new message?  Callbacks to the HASS app are forbidden (but still working fine) according to @ReneTode .

> It is possible to access all MQTT api from a HASS app by making use of the service call directly.


Well, I have been mislead by that AD provides an mqtt  plugin with an API. My conclusion is: don't use the plugin, try to find another solution.

**Comment by ReneTode** [comment] 2021-01-30 19:27
> So how did MQTT tell HASS there was a new message?

by inheriting from the hass plugin you can do anything from hassapi.



for example a part from my mysensors app:
```
import appdaemon.plugins.hass.hassapi as hass
import datetime
     
class mysensors(hass.Hass):
    def initialize(self):
        self.switch_state = ["off","on"]
        self.gatewaydata = self.args["gateway"]
        self.gatewayname = self.gatewaydata["name"]
        self.nodes = self.gatewaydata["nodes"]
        self.topic = self.gatewaydata["topic"]
        self.topic_out = self.topic + "-out"
        self.topic_in = self.topic + "-in" 
        self.listen_event(self.message_comes_in, event = self.topic, namespace = self.topic) 
        for nodenr, nodesettings in self.nodes.items():
            nodename = nodesettings["name"]
            node_friendly_name = nodesettings["friendly_name"]
            for childnr, childsettings in nodesettings["children"].items():
                platform = childsettings["platform"]
                entity = "{}.{}_{}_{}".format(platform, nodename, nodenr, childnr)
                friendly_name = node_friendly_name + " " + childsettings["friendly_name"]
                self.mylog2(entity)
                entity_settings = {"initial": "off"}
                entity_settings["attributes"] = {"friendly_name": friendly_name, "gateway": self.gatewayname, "Node id": nodenr, "Child id": childnr,"type": childsettings["type"],"var_type": childsettings["var_type"]}
                if entity_settings["attributes"]["type"] == "S_MOTION":
                    entity_settings["attributes"]["device_class"] = "motion"
                if "reset" in childsettings:
                    entity_settings["re_initialise"] = True
                self.get_app("create_entities_mysensors_{}".format(self.gatewayname)).build_entity(entity,entity_settings)
                if platform != "sensor" and platform != "binary_sensor":
                    self.listen_state(self.command_going_out, entity, nodenr = nodenr, childnr = childnr, childsettings = childsettings)
        self.log("Gateway connected")
        return
```
in this case i listen to mqtt events, and when they come in, i use the mqtt data to do stuff in HA.
but its also possible inheriting from mqtt
for example my milight app.

that app inherits from mqtt, listens to mqtt events, and then sends other mqtt events to HA
creating HA lights that HA automaticly detects, without configuring HA.

so it was already possible to combine the both plugins before "the new way" was created.
but certainly everything is possible with the new way.

**Comment by skannea** [comment] 2021-01-31 15:33
@ReneTode 

>  in this case i listen to mqtt events, and when they come in, i use the mqtt data to do stuff in HA.

Do you have an MQTT plugin app that has a callback function for "MQTT_MESSAGE" and that fires the topic-events that this app listens for? 

Can you tell if it is OK to do like below. I tried it with success!  

```
class H(hass.Hass): 
  def initialize(self):  
    self.listen_event( self.onMessage, "MQTT_MESSAGE", namespace='mqtt', topic='testx') 
      
  def terminate(self): 
    pass

  def onMessage( self, event_name, data, kwargs):  
    self.log( 'Topic: ' + data['topic'] ) 

```    
Even the topic fitering works. And the callback is cancelled at reload.

**Comment by ReneTode** [comment] 2021-02-01 00:57
yes i believe that is ok.
but i never listen to MQTT_MESSAGE
you can set the event name in appdaemon.yaml

like:
```
    MYSENSORS_HUISKAMER:
      type: mqtt
      verbose: False
      client_host: ip
      client_port: port
      client_id: AD_mysensors_huiskamer
      namespace: mysensors-huiskamer
      event_name: mysensors-huiskamer
      client_topics:
        - mysensors-huiskamer-out/#
```
and then you can listen to "mysensors-huiskamer"
and that is then always the topic: "mysensors-huiskamer-out/#"

in that case i use this in an hass inherited app:
```
        self.listen_event(self.message_comes_in, event = "mysensors-huiskamer", namespace = "mysensors-huiskamer") 
```
but you can also use:
```
class H(hass.Hass): 
  def initialize(self):  
    self.listen_event( self.onMessage, "MQTT_MESSAGE", namespace='mqtt', topic='testx') 
      
  def terminate(self): 
    pass

  def onMessage( self, event_name, data, kwargs):  
    some_calc = 2 * data["some_info"]
    self.fire_event("some_name", calc_var = some_calc, namespace = "some_custom_namespace")
```
and listen for that event elsewhere.
    
but your app is the most common used way for hass users that use "old style"
and in that case also this is used:
```
    self.call_service("mqtt/publish", topic="something", payload="something")
```
which fires the publish from inside HA.
    
> And the callback is cancelled at reload.
    
off course, you got the listener and the callback in the same app.

**Comment by skannea** [comment] 2021-02-01 11:06
@ReneTode Thanks! No further questions from me. For the moment...

**Comment by ReneTode** [comment] 2021-02-01 16:08
if you got other AD questions, you are always welcome on our discord.

**Comment by Odianosen25** [comment] 2021-02-10 11:17
Closing this please

**Closed by Odianosen25** 2021-02-10 11:17 UTC
