### ISSUE TITLE
Callback Clean Up issue

### ISSUE THREAD

**Issue by dlashua** [AppDaemon/appdaemon#671] opened 2019-09-12 18:29 UTC
AD Version: PR# 670, though, I don't see why this wouldn't happen in "dev" branch as well.

When terminating a VERY busy App with lots of callbacks, I see the following error:
```
2019-09-12 13:24:04.543407 INFO AppDaemon: App 'test' deleted
2019-09-12 13:24:04.553889 INFO AppDaemon: Found 0 total apps
2019-09-12 13:24:04.620547 WARNING test: ------------------------------------------------------------
2019-09-12 13:24:04.620932 WARNING test: Unexpected error in worker for App test:
2019-09-12 13:24:04.621379 WARNING test: Worker Ags: {'pin_thread': 0, 'id': '0d90a6ed6aea4ff0b8d2cc25105676a7', 'objectid': '16e8dd4aefbb4db987e2ee41b68bdf11', 'function': <bound method MakeStuff.toggle of <test.MakeStuff object at 0x110a56a20>>, 'kwargs': {'__thread_id': 'thread-0', 'entity': 'binary_sensor.automake_12'}, 'type': 'scheduler', 'name': 'test', 'pin_app': True}
2019-09-12 13:24:04.621853 WARNING test: ------------------------------------------------------------
2019-09-12 13:24:04.665501 WARNING test: Traceback (most recent call last):
  File "/Users/daniel/code/appdaemon/appdaemon/threading.py", line 641, in worker
    funcref(self.AD.sched.sanitize_timer_kwargs(app, args["kwargs"]))
  File "/Users/daniel/appdaemon/conf/apps/test.py", line 56, in toggle
    self.run_in(self.toggle, delay, entity=entity)
  File "/Users/daniel/code/appdaemon/appdaemon/adapi.py", line 1986, in run_in
    name, exec_time, callback, False, None, **kwargs
  File "/Users/daniel/code/appdaemon/appdaemon/utils.py", line 247, in run_coroutine_threadsafe
    result = future.result(self.AD.internal_function_timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/concurrent/futures/_base.py", line 405, in result
    return self.__get_result()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/concurrent/futures/_base.py", line 357, in __get_result
    raise self._exception
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/asyncio/tasks.py", line 240, in _step
    result = coro.send(None)
  File "/Users/daniel/code/appdaemon/appdaemon/scheduler.py", line 265, in insert_schedule
    pin_app = self.AD.app_management.objects[name]["pin_app"]
KeyError: 'test'

2019-09-12 13:24:04.666045 WARNING test: ------------------------------------------------------------
2019-09-12 13:24:04.668365 INFO AppDaemon: _threading: Entity app.test created in namespace: admin
2019-09-12 13:24:04.674276 WARNING AppDaemon: Found stale callback for test - discarding
```
  
  
  
test.py
```python
class MakeStuff(hass.Hass):

    def initialize(self):
        self.make = self.args.get('number', 1)
        self.run_in(self.start, 1)

    def start(self, kwargs):
        for i in range(0, self.make):
            entity = self.entity_id(i)
            self.set_state(entity, state="off")
            delay = random.randint(1, 5)
            self.run_in(self.toggle, delay, entity=entity)

    def toggle(self, kwargs):
        entity = kwargs['entity']
        current = self.get_state(entity, attribute="state")
        new = "on"
        if current == "on":
            new = "off"
        self.set_state(entity, state=new)
        delay = random.randint(1, 5)
        self.run_in(self.toggle, delay, entity=entity)

    def entity_id(self, num):
        return "binary_sensor.automake_{}".format(num)
```
  
  
  
test.yaml
```yaml
 test:
   module: test
   class: MakeStuff
   number: 100
```

**Comment by acockburn** [comment] 2019-09-14 19:37
When you say terminating - how did you terminate it?

**Comment by Odianosen25** [comment] 2019-09-14 20:35
I think I have seen this before, like if the app was to simply restart, this issue could show up

**Comment by dlashua** [comment] 2019-09-15 12:08
@acockburn I commented the app out of YAML and saved the file.

**Comment by acockburn** [comment] 2019-09-15 13:23
OK, yeah, it's a race condition. I'll take a look at how best to fix it.

**Comment by acockburn** [comment] 2023-03-04 13:27
Ran the test just now against dev and was unable to reproduce, considering the length of time I am closing this.

**Closed by acockburn** 2023-03-04 13:27 UTC
Labels: bug
