### ISSUE TITLE
Hass API stop working when i include additional python package in the GUI section

### ISSUE THREAD

**Issue by glockdd** [AppDaemon/appdaemon#2057] opened 2024-09-02 18:57 UTC
### What happened?

I need to retrive some weather forecast for my irrigation system, but when i include the open meteo package the application can't read hass state anymore. 

Appdaemon start, install the necessary package, run the application, try to communicate with hass but the result value was None. 

![Immagine 2024-09-02 205043](https://github.com/user-attachments/assets/27fd87da-26e5-4362-b8df-e85dec497399)

### Version

4.4.2

### Installation type

Home Assistant add-on

**Comment by acockburn** [comment] 2024-09-02 21:33
That's not very much to go on - any errors in the log file? Can you share your app code? What call was returning `None`? Did it all work as expected prior to installing the package?

**Comment by glockdd** [comment] 2024-09-04 13:25
The code is attached 
[file.zip](https://github.com/user-attachments/files/16871187/file.zip)

Normally, before importing library in appdaemon the code work well, but when i import the library the code stop working. For example `self.automatic_irrigation_time = self.get_state("input_datetime.orario_irrigazione")` return None when before return something like that "07:00:00". 

Thanks

**Comment by acockburn** [comment] 2024-09-04 14:04
OK, then it seems like this is a duplicate of #2013. There should have been some logging that would have helped us identify this more quickly. That issue has a workaround in it I believe, and It should be fixed in the current dev branch, and we will be releasing a new AD version in the next few weeks that will have the fix in it.

**Closed by acockburn** 2024-09-04 14:04 UTC
Labels: bug, Duplicate

**Comment by glockdd** [comment] 2024-09-04 14:44
There is something i can do?
