### ISSUE TITLE
Reschedule on daylight saving time change?

### ISSUE THREAD

**Issue by electrofloat** [AppDaemon/appdaemon#952] opened 2020-03-30 08:25 UTC
Hi!

Do we need to reschedule all the schedules manually (aka restart appdaemon) when DST changes, or should this happen automatically?

We just had a DST change and all the schedules were off by 1 hour.

**Comment by acockburn** [comment] 2020-03-30 11:18
This is a known issue and is currently being worked on in dev and will be in the next version. For now, the workaround is to restart AD after the change.

**Comment by adamcohenrose** [comment] 2020-10-27 10:59
is this still an issue? the docs at https://appdaemon.readthedocs.io/en/latest/APPGUIDE.html#plugin-reloads seem to indicate that appdaemon will reload if DST changes...

**Comment by electrofloat** [comment] 2020-10-27 17:09
I'm not using schedules at the moment, so I cannot test it unfortunately. But feel free to close this if it is implemented and works now.

**Comment by ReneTode** [comment] 2020-10-28 01:15
for me most of it did work except the run_daily schedules.
they were still off for 1 hour.

**Comment by acockburn** [comment] 2020-10-28 10:41
That issue should have been fixed in the last release. So now, no restart for a DST change, and the time stamps for run daily etc. should be rewritten to conpensate.

**Comment by ReneTode** [comment] 2020-10-29 00:59
im on 4.0.6 (dev after the last release.)

i got the message that DST was detected.
time was changed, and most things did run as expected.
but the run_daily scheduled things did run on the summer time, and not on the new time (and i could see in the AI that they were on the wrong time)

**Comment by deviantintegral** [comment] 2022-11-06 12:48
This appears to still be an issue. We changed DST today, and a `run_daily` automation didn't run. There was no indication of errors or restarting apps in the logs.

**Comment by acockburn** [comment] 2022-11-06 13:13
There are too many corner cases to actually get this to work reliably all the time and the code is very complex. My thought is to revert to the old system which just restarts the apps when the time changes and let the app take care of it. That upset some users with multiple apps but it’s more deterministic than trying to rewrite existing scheduler entries.

**Comment by deviantintegral** [comment] 2022-11-06 16:21
Could there be a config option to opt out of the restart behaviour system wide, or per app?

Another thought is that Home Assistant seems to handle this fine, so there may be some code offering ideas on how to architect this.

**Comment by acockburn** [comment] 2023-03-04 13:48
Duplicate of #1485 - will be tracked there.

**Closed by acockburn** 2023-03-04 13:48 UTC
Labels: bug
