### ISSUE TITLE
Pi install guide

### ISSUE THREAD

**Issue by timdonovanuk** [AppDaemon/appdaemon#126] opened 2017-08-24 14:00 UTC
After much trouble trying the supposed easy "pip3 install" method I thought I'd try the docker install, but it fails with:

Status: Downloaded newer image for acockburn/appdaemon:latest
standard_init_linux.go:178: exec user process caused "exec format error"

Since most people are running HA on a Pi, it would be really handy if someone with technical knowledge of appdaemon could run through and document the install process of appdaemon on a vanilla Pi (running Hassbian or raspbian). 

I don't think I'm doing anything out of the ordinary (simply a Pi 3, with latest Hassbian) but the install docs don't get me even past step 1, whether I try pip or docker. 

And ultimately all I wanted was a nicer dashboard! :)

**Comment by acockburn** [comment] 2017-08-24 14:49
Unfortunately, docker hub will only let me upload one image and it doesn't work for the PI. It is possible to build your own image from the git repository - I'll add instructions for that in the next release.

**Comment by joebetsill** [comment] 2017-08-24 14:55
>Status: Downloaded newer image for acockburn/appdaemon:latest
standard_init_linux.go:178: exec user process caused "exec format error"

This error is usually (always?) given when the architecture of the docker image does not match the architecture of the system you're trying to run it on. In this case, the RPI is arm, and the python image the docker image pulls from is x86.

It seems it's as simple as replacing 

`FROM python:3.6`

with

`FROM arm32v6/python:alpine3.6`

in the Dockerfile to resolve the issue.

At least, from what little I know of docker. I cloned the repo and made the change myself and everything seemed to work fine. I did minimal testing, though.

**Comment by acockburn** [comment] 2017-08-24 15:31
Yes, that's pretty much it - the reason I need to update the docs is because they reference the docker hub method of installation, weheras the raspberry method will need to be a manual clone of the repository and build of the image which is a little more involved.

**Comment by torkildr** [comment] 2017-08-27 09:45
I'm rolling my own image on docker hub, for now.

I'm doing my best to keep it current with master

https://hub.docker.com/r/torkildr/rpi-appdaemon/

**Comment by acockburn** [comment] 2017-12-23 21:30
Adding this to the official docs if you don;t mind :)

**Comment by werdnum** [comment] 2018-03-09 03:28
Hi -- I don't see any instructions about building your own image on https://appdaemon.readthedocs.io/en/latest/DOCKER_TUTORIAL.html

**Comment by acockburn** [comment] 2018-03-09 12:53
http://appdaemon.readthedocs.io/en/latest/INSTALL.html#raspberry-pi-docker

**Comment by werdnum** [comment] 2018-03-09 14:24
Thanks! Created https://github.com/home-assistant/appdaemon/pull/258 to update docs. Will need to get approval for signing the CLA first (I work somewhere that claims all my IP)

**Comment by acockburn** [comment] 2018-03-09 16:22
Thanks - happy to merge when you get that approval.

**Comment by x99percent** [comment] 2018-03-15 17:56
You could add a Dockerfile-rpi with the needed change(s) to your github, then it could be built directly on the Pi with:

```
docker build -t appdaemon -f Dockerfile-rpi https://github.com/home-assistant/appdaemon.git
```

**Comment by acockburn** [comment] 2018-03-16 16:20
That's a good idea - I'll re-open this to remind me to do that - although I might need help with the testing :)

**Comment by jwl17330536** [comment] 2018-12-14 21:58
> http://appdaemon.readthedocs.io/en/latest/INSTALL.html#raspberry-pi-docker

Am I the only one who finds this incomplete of an explanation?  I'm pretty new to docker and am lost on what I need to do to make this work.

**Comment by ReneTode** [comment] 2018-12-15 00:32
i guess the problem is that you are new to docker.
as no docker user i understand this:
- docker uses a kind of configuration file that you need to edit.
- then you need to rebuild the docker
- then you can follow the instructions from the normal docker instructions

and to make it easy there is a link to someone that has done step 1 and 2 for you.

**Comment by jwl17330536** [comment] 2018-12-15 15:58
Big fan of your passive aggressiveness. I stated my newness to this and asked one simple question, am I the only one that finds this incomplete? 

To your first bullet point, I’m aware. To your second, I read that. To your third, I got that too. More information on the how you do the 1st and 2nd is what I don’t get. Again, I said I was new to docker and if this isn’t something that no one wants to document, I get it. Hence why I asked. 

And the link didn’t work on my Pi. It failed with multiple errors. Again, for the nth time it could all be me. It was a simple question, but sure go ahead and flame away.

**Comment by acockburn** [comment] 2018-12-15 16:42
Please, no arguments here. @jwl17330536 - the best place to get assistance is on the Home Assistant forum, this area is used more for reporting issues. Perhaps when you manage to figure this out, with whatever help we can give you, you would help out by improving the docs for other users.

**Comment by Odianosen25** [comment] 2021-02-26 20:02
The docs for building the image now allows to specify base images that are friendly with the Pi, so will be closing this for now.

teavtss

**Closed by Odianosen25** 2021-02-26 20:02 UTC
Labels: enhancement
