### ISSUE TITLE
The client is using an unsupported version of the Socket.IO or Engine.IO

### ISSUE THREAD

**Issue by juan11perez** [AppDaemon/appdaemon#1348] opened 2021-08-27 02:00 UTC
The above error is back. 
Recommended action on this [site](https://stackoverflow.com/questions/66069215/the-client-is-using-an-unsupported-version-of-the-socket-io-or-engine-io-protoco) fixed it.

`pip install --upgrade python-socketio==4.6.0
pip install --upgrade python-engineio==3.13.2
pip install --upgrade Flask-SocketIO==4.3.1`

**Comment by acockburn** [comment] 2021-08-28 22:57
Fixed in dev

**Comment by teqali** [comment] 2021-09-10 17:58
when will it be fix?

**Comment by miraculixdruid** [comment] 2021-09-12 19:07
https://github.com/hassio-addons/addon-appdaemon/issues/156

**Comment by chiefcomm** [comment] 2021-09-20 03:54
When is this going to be fixed, 4.1.0 has crippled anyone using older displays (of which is a large proportion of the user base).

**Comment by acockburn** [comment] 2021-09-20 10:50
I have no idea - I don’t know what the problem is nor do I have any way to test it. If anyone can help me figure it out I’m happy to make the fix. In the meantime I suggest you downgrade to the last working version of appdaemon.

**Comment by chiefcomm** [comment] 2021-09-20 11:22
> I have no idea - I don’t know what the problem is nor do I have any way to test it. If anyone can help me figure it out I’m happy to make the fix. In the meantime I suggest you downgrade to the last working version of appdaemon.

Issue is a duplicate of #1335 @frenck explained the issue and the fix

**Comment by acockburn** [comment] 2021-09-28 21:34
thanks to a PR by @clyra this should be fixed in dev now

**Comment by NicolasSenetLarson** [comment] 2022-10-13 23:36
I'm still getting this error on AppDaemon 4.2.1.
Is there a reason that appdaemon/appdaemon/assets/javascript/socket.io.js is kept at version 2.1.1?

**Comment by acockburn** [comment] 2023-03-03 22:56
AT this point I am pretty much dropping support for older iPads, unless someone can come up with a PR to fix it - I don't have the means to test it.

**Closed by acockburn** 2023-03-03 22:56 UTC
